services:
  # 1. 데이터베이스 서비스
  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: kangdb
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  # 2. 내 스프링 부트 앱 서비스
  app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # 컨테이너끼리는 서비스 이름인 'db'로 통신합니다.
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/kangdb?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}